from colorama import Fore, Back, Style, init

def formatter(text):
	text = text.replace("{Fore.RED}", Fore.RED)
	text = text.replace("{Fore.BLACK}", Fore.BLACK)
	text = text.replace("{Fore.GREEN}", Fore.GREEN)
	text = text.replace("{Fore.BLUE}", Fore.BLUE)
	text = text.replace("{Fore.WHITE}", Fore.WHITE)
	text = text.replace("{Fore.CYAN}", Fore.CYAN)
	text = text.replace("{Fore.MAGENTA}", Fore.MAGENTA)
	text = text.replace("{Fore.YELLOW}", Fore.YELLOW)
	text = text.replace("{Fore.LIGHTBLACK_EX}", Fore.LIGHTBLACK_EX)
	text = text.replace("{Fore.LIGHTRED_EX}", Fore.LIGHTRED_EX)
	text = text.replace("{Fore.LIGHTGREEN_EX}", Fore.LIGHTGREEN_EX)
	text = text.replace("{Fore.LIGHTBLUE_EX}", Fore.LIGHTBLUE_EX)
	text = text.replace("{Fore.LIGHTWHITE_EX}", Fore.LIGHTWHITE_EX)
	text = text.replace("{Fore.LIGHTCYAN_EX}", Fore.LIGHTCYAN_EX)
	text = text.replace("{Fore.LIGHTMAGENTA_EX}", Fore.LIGHTMAGENTA_EX)
	text = text.replace("{Fore.LIGHTYELLOW_EX}", Fore.LIGHTYELLOW_EX)
	text = text.replace("{Fore.RESET}", Fore.RESET)
	text = text.replace("{Back.RED}", Back.RED)
	text = text.replace("{Back.BLACK}", Back.BLACK)
	text = text.replace("{Back.GREEN}", Back.GREEN)
	text = text.replace("{Back.BLUE}", Back.BLUE)
	text = text.replace("{Back.WHITE}", Back.WHITE)
	text = text.replace("{Back.CYAN}", Back.CYAN)
	text = text.replace("{Back.MAGENTA}", Back.MAGENTA)
	text = text.replace("{Back.YELLOW}", Back.YELLOW)
	text = text.replace("{Back.LIGHTBLACK_EX}", Back.LIGHTBLACK_EX)
	text = text.replace("{Back.LIGHTRED_EX}", Back.LIGHTRED_EX)
	text = text.replace("{Back.LIGHTGREEN_EX}", Back.LIGHTGREEN_EX)
	text = text.replace("{Back.LIGHTBLUE_EX}", Back.LIGHTBLUE_EX)
	text = text.replace("{Back.LIGHTWHITE_EX}", Back.LIGHTWHITE_EX)
	text = text.replace("{Back.LIGHTCYAN_EX}", Back.LIGHTCYAN_EX)
	text = text.replace("{Back.LIGHTMAGENTA_EX}", Back.LIGHTMAGENTA_EX)
	text = text.replace("{Back.LIGHTYELLOW_EX}", Back.LIGHTYELLOW_EX)
	text = text.replace("{Back.RESET}", Back.RESET)
	text = text.replace("{Style.UNDERLINE}", "\033[4m")
	text = text.replace("{Style.BRIGHT}", Style.BRIGHT)
	text = text.replace("{Style.END}", "\033[0m")
	text = text.replace("{Style.RESET_ALL}", Style.RESET_ALL)
	return text

if __name__ == "__main__": pass
